### ISSUE TITLE
[PATCH] avoid deprecated rb_thread_blocking_region

### ISSUE THREAD

**Issue by nocode** [codeslinger/sendfile#3]
http://bogomips.org/ruby-sendfile.git/patch?id=7bde88afdad

This is for compatibility with future releases of mainline ruby,
as rb_thread_blocking_region is removed in r44955 of ruby trunk.
I've tested this with the following Rubies:

ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
ruby 1.9.3p484 (2013-11-22 revision 43786) [x86_64-linux]
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-linux]
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-linux]
ruby 2.2.0dev (2014-02-15 trunk 44966) [x86_64-linux]
rubinius 2.2.4.n35 (2.1.0 fa307b6a 2014-02-04 JI) [x86_64-linux-gnu]

You may also pull: git pull git://bogomips.org/ruby-sendfile rtrunk
commit 7bde88afdade68477e31eea29783288b0a5f4810

(I do not endorse GitHub, git is a distributed system and GitHub treats external repos as second class citizens).

**Comment by codeslinger** [comment]
If you want me to accept this into the upstream, you will have to open a pull request on Github, as that's where I've chosen to host this project. Thanks.

**Comment by nocode** [comment]
Hi Toby, I urge you to reconsider this position.  The whole point of
distributed version control is repositories on different hosts may
interoperate, whether it be via patches or pull requests (both options I
provide).

You've accepted my contributions in the past, even.

I suggest reading the following on why it's important to use free tools:
http://mako.cc/writing/hill-free_tools.html

**Comment by codeslinger** [comment]
Applied and released 1.2.2 to RubyGems. Thanks.
